### ISSUE TITLE
Add ecoCode-javascript plugin to SonarQube Marketplace

### ISSUE THREAD

**Issue by utarwyn** [green-code-initiative/ecoCode-javascript#15]
## Description

Now that *ecoCode* JavaScript plugin is standalone, it's time to prepare its arrival on the SonarQube marketplace 🚀 
Below is the todo-list, based on the one created by @jycr for other plugins.

## TODO List

- [x] Create a standalone SonarQube plugin (#14)
- [x] Use the centralized rules artifact in this plugin (#16)
- [x] Rename rule IDs to follow convention (`EC` prefix followed by a number) (Do not forget to add `@DeprecatedRuleKey` annotation when needed)
- [x] Check if the license is [Free-Libre / Open Source Software](http://opensource.org/licenses)
- [x] Check documentation is available online in English
- [x] Release 1.4.0 with a release notes that reflect all significant changes in the version
- [x] Check plugin key (must be short and unique, lowercase, no camelcase, composed only of [a-z0-9], related to the name of your plugin not just the name of a language - e.g. cannot be java, rust, js/javascript, …)
    - [`ecocodejavascript`](https://github.com/green-code-initiative/ecoCode-javascript/blob/main/sonar-plugin/pom.xml#L128)
- [x] Check plugin description (must not be misleading in terms of content, the code needs to do pretty much what the name and description say it does)
- [x] Provide the necessary details to be able to test the plugin
- [x] Check [SonarCloud](https://sonarcloud.io/) quality gate is green when doing a release
- [x] Check platform requirements (it runs on JRE 11 with SonarQube 9.9 LTS and 10.x)
- [x] Check no export of files to other servers / services from within SonarQube or during SonarQube analysis
- [x] Create discussion on SonarSource community

More information:
* [Sonarsource community - Deploying to the Marketplace](https://community.sonarsource.com/t/deploying-to-the-marketplace/35236)
* [github/sonar-update-center-properties](https://github.com/SonarSource/sonar-update-center-properties)

**Comment by JayPe69** [comment]
+1, I wanted to use this plugin, but I didn't find it on the market place.
I know I can install it manually, but it will be very nice to have it on the market place

**Comment by utarwyn** [comment]
Hello @JayPe69, thank you for your interest in using our plugin!

Indeed, the plugin isn't yet available on the marketplace, which is our priority today (a few other issues are delaying the process, sorry for this).

You can find the latest available version of ecoCode-javascript in the main ecoCode repository (released before the split):
https://github.com/green-code-initiative/ecoCode/releases/tag/1.3.0

**Comment by JayPe69** [comment]
@utarwyn , thanks a lot.

In the readme file of this plugin, the link to get the binary file is : 
https://github.com/green-code-initiative/ecoCode-javascript/releases

I guess you should change it to :
https://github.com/green-code-initiative/ecoCode/releases

Thanks again, I'll try it

**Comment by JayPe69** [comment]
@utarwyn sorry but, now the plugin is installed, do I have to configure something special ?

![image](https://github.com/green-code-initiative/ecoCode-javascript/assets/37151973/f06d425c-9eed-4ae9-9240-59d58d5249c1)

I don't see any new rules or new Quality Profile.  
Thanks

**Comment by utarwyn** [comment]
This version works with SonarQube external rules system. This means that the rules are not displayed directly in the SonarQube interface ([more info here](https://github.com/green-code-initiative/ecoCode/blob/1.3.0/javascript-plugin/README.md)). This is a technical limitation of SonarQube.

But we've found a way around this problem for the next version of the plugin! It will display the rules like any other SonarQube plugin. The "unreleased" part of the [changelog](https://github.com/green-code-initiative/ecoCode-javascript/blob/main/CHANGELOG.md) exposes this change among many others. We really hope to be able to propose it very soon.

Sorry for the misunderstanding. The current README contains the documentation for the new version of the plugin, which has not yet been released.

**Comment by utarwyn** [comment]
@JayPe69
A new stable version of the plugin is available! This one is standalone and display rules as regular ones in the SonarQube UI.
The process to add the plugin to the marketplace will be sstarted in the next few days, as soon as possible.

https://github.com/green-code-initiative/ecoCode-javascript/releases/tag/1.4.0

**Comment by JayPe69** [comment]
@utarwyn , thanks a lot for this new stable version.
As I'm using the DeveloperEdition of SonarQube, I have to install it manually anyway.
I'll give you some feedbacks.

**Comment by utarwyn** [comment]
The discussion has been created on Sonar Community platform:
https://community.sonarsource.com/t/new-plugin-ecocode-javascript-requesting-inclusion-in-sonarqube-marketplace/103808

Related PR to integrate the plugin to the marketplace is here:
https://github.com/SonarSource/sonar-update-center-properties/pull/454

**Comment by utarwyn** [comment]
Request has been accepted! **The plugin will be available very soon from the official marketplace** 🥳 
But there are a few changes to be made for the next version of the plugin. Check #30 to have more info.
